# Generated by Django 4.0.3 on 2022-03-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='firstName',
            new_name='companyName',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lastName',
        ),
    ]
