# Generated by Django 4.0.3 on 2022-04-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('Town_sale', models.FloatField(blank=True, null=True)),
                ('Local_sale', models.FloatField(blank=True, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
                ('Date', models.DateField(null=True)),
            ],
        ),
    ]
