# Generated by Django 4.0.3 on 2022-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startup', '0002_product_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
