# Generated by Django 4.0.3 on 2022-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=70)),
                ('Last_name', models.CharField(default='', max_length=200)),
                ('Address', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
