# Generated by Django 4.0.3 on 2022-03-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=70, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('Address', models.CharField(blank=True, max_length=70, null=True)),
                ('joining_date', models.DateField()),
                ('Technology', models.CharField(max_length=100)),
            ],
        ),
    ]
