# Generated by Django 4.0.3 on 2022-03-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='joining_date',
            new_name='Joining_date',
        ),
    ]
