# Generated by Django 3.2 on 2022-02-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='employees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employees'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
